<%
  def git_branch
    %x{git name-rev --name-only HEAD}.strip
  end
%>

login: &login
  username: root
  password:

development:
  adapter: sqlite3
  database: db/rails-bootstrap_<%= git_branch %>_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/rails-bootstrap_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/rails-bootstrap_production.sqlite3
  pool: 5
  timeout: 5000
